"""hhh8

Revision ID: 0187745c7abd
Revises: 362cab2e17a6
Create Date: 2022-02-08 06:27:40.308010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0187745c7abd'
down_revision = '362cab2e17a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('conversation_opened', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation', 'conversation_opened')
    # ### end Alembic commands ###
