"""hhh6

Revision ID: 1978904cd413
Revises: 6f6039d0a2ed
Create Date: 2022-02-01 12:42:51.188834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1978904cd413'
down_revision = '6f6039d0a2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_rules', sa.Column('initial_assignment_id', sa.Integer(), nullable=True))
    op.add_column('conversation_rules', sa.Column('user_assigned_when_noone_is_online_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversation_rules', 'users', ['initial_assignment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_rules', 'users', ['user_assigned_when_noone_is_online_id'], ['id'], ondelete='CASCADE')
    op.drop_column('conversation_rules', 'user_assigned_when_noone_is_online')
    op.drop_column('conversation_rules', 'initial_assignment')
    op.add_column('default_team', sa.Column('bot_selected_id', sa.Integer(), nullable=True))
    op.add_column('default_team', sa.Column('initial_assignment_id', sa.Integer(), nullable=True))
    op.add_column('default_team', sa.Column('user_assigned_when_noone_is_online_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'default_team', ['bot_selected_id'])
    op.create_unique_constraint(None, 'default_team', ['user_assigned_when_noone_is_online_id'])
    op.create_unique_constraint(None, 'default_team', ['initial_assignment_id'])
    op.create_foreign_key(None, 'default_team', 'users', ['initial_assignment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'default_team', 'users', ['user_assigned_when_noone_is_online_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'default_team', 'bot', ['bot_selected_id'], ['id'], ondelete='CASCADE')
    op.drop_column('default_team', 'user_assigned_when_noone_is_online')
    op.drop_column('default_team', 'initial_assignment')
    op.drop_column('default_team', 'bot_selected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('default_team', sa.Column('bot_selected', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('default_team', sa.Column('initial_assignment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('default_team', sa.Column('user_assigned_when_noone_is_online', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'default_team', type_='foreignkey')
    op.drop_constraint(None, 'default_team', type_='foreignkey')
    op.drop_constraint(None, 'default_team', type_='foreignkey')
    op.drop_constraint(None, 'default_team', type_='unique')
    op.drop_constraint(None, 'default_team', type_='unique')
    op.drop_constraint(None, 'default_team', type_='unique')
    op.drop_column('default_team', 'user_assigned_when_noone_is_online_id')
    op.drop_column('default_team', 'initial_assignment_id')
    op.drop_column('default_team', 'bot_selected_id')
    op.add_column('conversation_rules', sa.Column('initial_assignment', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('conversation_rules', sa.Column('user_assigned_when_noone_is_online', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversation_rules', type_='foreignkey')
    op.drop_constraint(None, 'conversation_rules', type_='foreignkey')
    op.drop_column('conversation_rules', 'user_assigned_when_noone_is_online_id')
    op.drop_column('conversation_rules', 'initial_assignment_id')
    # ### end Alembic commands ###
