"""hhh7

Revision ID: 362cab2e17a6
Revises: 1978904cd413
Create Date: 2022-02-04 08:21:01.301644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import models

# revision identifiers, used by Alembic.
revision = '362cab2e17a6'
down_revision = '1978904cd413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('sender', models.ChoiceType(models.ChatStorage.SENDER_CHOICES), nullable=True),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_storage_id'), 'chat_storage', ['id'], unique=False)
    op.drop_column('conversation', 'confidence_level')
    op.drop_column('conversation', 'response')
    op.drop_column('conversation', 'intent_detected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('intent_detected', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('conversation', sa.Column('confidence_level', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_storage_id'), table_name='chat_storage')
    op.drop_table('chat_storage')
    # ### end Alembic commands ###
