"""hhh13

Revision ID: 47cc152d335a
Revises: 9103dfe758d1
Create Date: 2022-04-08 16:18:30.284445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cc152d335a'
down_revision = '9103dfe758d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_options', 'auto_resolve_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_options', sa.Column('auto_resolve_time', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
