"""hhh9

Revision ID: 50d9c63b54aa
Revises: 0187745c7abd
Create Date: 2022-04-04 11:05:19.796337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d9c63b54aa'
down_revision = '0187745c7abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('last_fallback_emailed_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_fallback_emailed_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_fallback_emailed_time')
    op.drop_column('customers', 'last_fallback_emailed_time')
    # ### end Alembic commands ###
