"""hhh17

Revision ID: 5d5ebaf272a9
Revises: 24b14602a2df
Create Date: 2022-04-11 16:59:29.396511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5ebaf272a9'
down_revision = '24b14602a2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_templates', sa.Column('message_subject', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_templates', 'message_subject')
    # ### end Alembic commands ###
