"""hhh5

Revision ID: 6f6039d0a2ed
Revises: 5423bf5afb90
Create Date: 2022-01-24 14:14:08.578621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6039d0a2ed'
down_revision = '5423bf5afb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_bot_platform', sa.Column('platform_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_bot_platform', 'platform_name')
    # ### end Alembic commands ###
