"""hhh14

Revision ID: 8130d4902fbd
Revises: 47cc152d335a
Create Date: 2022-04-08 16:24:15.638517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8130d4902fbd'
down_revision = '47cc152d335a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
