"""hhh12

Revision ID: 9103dfe758d1
Revises: d15d1d1ef262
Create Date: 2022-04-08 15:14:14.413839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9103dfe758d1'
down_revision = 'd15d1d1ef262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
