"""hhh10

Revision ID: 9db8ed047a1e
Revises: 50d9c63b54aa
Create Date: 2022-04-05 18:25:19.830899

"""
from alembic import op
import sqlalchemy as sa
import models


# revision identifiers, used by Alembic.
revision = '9db8ed047a1e'
down_revision = '50d9c63b54aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_chat_lead_collection_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prechatlead_parent_id', sa.Integer(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('field_type', models.ChoiceType(models.PreChatLeadCollectionFields.FIELD_TYPE_CHOICES), nullable=True),
    sa.Column('field_name', sa.String(length=150), nullable=True),
    sa.Column('place_holder', sa.String(length=150), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prechatlead_parent_id'], ['pre_chat_lead_collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_chat_lead_collection_fields_id'), 'pre_chat_lead_collection_fields', ['id'], unique=False)
    op.drop_column('account_options', 'enable_prechat_lead')
    op.drop_column('account_options', 'prechat_lead_collection_heading')
    op.add_column('pre_chat_lead_collection', sa.Column('enable_prechat_lead', sa.Boolean(), nullable=True))
    op.add_column('pre_chat_lead_collection', sa.Column('prechat_lead_collection_heading', sa.String(length=200), nullable=True))
    op.drop_column('pre_chat_lead_collection', 'field_name')
    op.drop_column('pre_chat_lead_collection', 'place_holder')
    op.drop_column('pre_chat_lead_collection', 'field_type')
    op.drop_column('pre_chat_lead_collection', 'is_mandatory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pre_chat_lead_collection', sa.Column('is_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pre_chat_lead_collection', sa.Column('field_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pre_chat_lead_collection', sa.Column('place_holder', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('pre_chat_lead_collection', sa.Column('field_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('pre_chat_lead_collection', 'prechat_lead_collection_heading')
    op.drop_column('pre_chat_lead_collection', 'enable_prechat_lead')
    op.add_column('account_options', sa.Column('prechat_lead_collection_heading', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('account_options', sa.Column('enable_prechat_lead', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pre_chat_lead_collection_fields_id'), table_name='pre_chat_lead_collection_fields')
    op.drop_table('pre_chat_lead_collection_fields')
    # ### end Alembic commands ###
