"""hhh1

Revision ID: acc14daf274e
Revises: 3cb638e025c4
Create Date: 2021-11-26 16:01:37.147589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc14daf274e'
down_revision = '3cb638e025c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'bot_photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('bot_photo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
