"""hhh11

Revision ID: d15d1d1ef262
Revises: 9db8ed047a1e
Create Date: 2022-04-05 18:44:08.658675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15d1d1ef262'
down_revision = '9db8ed047a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
