"""hhh15

Revision ID: d421bb71ce13
Revises: 8130d4902fbd
Create Date: 2022-04-08 16:28:57.938921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd421bb71ce13'
down_revision = '8130d4902fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_options', 'auto_resolve_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_options', sa.Column('auto_resolve_option', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
