"""hhh2

Revision ID: f35023ccf720
Revises: acc14daf274e
Create Date: 2021-11-26 16:02:13.366156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35023ccf720'
down_revision = 'acc14daf274e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('bot_photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'bot_photo')
    # ### end Alembic commands ###
